services:
  - type: web
    name: hai-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: PYTORCH_CUDA_ALLOC_CONF
        value: max_split_size_mb:128
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
    plan: standard  # This gives you 1GB RAM